### ISSUE TITLE
Wrong link on README table of contents

### ISSUE THREAD

**Issue by bernardoduarte** [hantuzun/awesome-clojurescript#49]
The README table of contents has a link with the following text `Awesome ClojureScript` that points [here](https://github.com/hantuzun/awesome-clojurescript#awesome-clojurescript), the way that it is written it comes after `Resources` so it should actually point [here](https://github.com/hantuzun/awesome-clojurescript#awesome-clojurescript-1).

**Comment by hantuzun** [comment]
Fixed now. Thanks.
